### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by Tikam02** [arpit0891/Plant-Disease-Detection-Web-application#36]
@arpit0891 Please provide the dataset link

**Comment by arpit0891** [comment]
Here: https://github.com/spMohanty/PlantVillage-Dataset

**Comment by Tikam02** [comment]
In code for test and train, you are referring to this right - https://github.com/spMohanty/PlantVillage-Dataset/tree/master/data_distribution_for_SVM

Or Raw data?

Because the dataset is distributed and I didn't get which dataset to be used for your code.
